name = "neoartifex"
main = "src/worker.ts"
compatibility_date = "2023-01-01"

# KV namespace configuration using environment variables
[[kv_namespaces]]
binding = "NEOARTIFEX_KV"
# Use the environment variable for the KV namespace ID
id = "${CLOUDFLARE_KV_NAMESPACE_ID}"